export const PUBLIC_HOLIDAY_LIST_GB = [
  {
    date: '2023-01-01',
    localName: "New Year's Day",
    name: "New Year's Day",
    countryCode: 'GB',
    fixed: false,
    global: false,
    counties: ['GB-NIR'],
    launchYear: null,
    types: ['Public'],
  },
  {
    date: '2023-01-02',
    localName: "New Year's Day",
    name: "New Year's Day",
    countryCode: 'GB',
    fixed: false,
    global: false,
    counties: ['GB-ENG', 'GB-WLS'],
    launchYear: null,
    types: ['Public'],
  },
  {
    date: '2023-01-02',
    localName: "New Year's Day",
    name: "New Year's Day",
    countryCode: 'GB',
    fixed: false,
    global: false,
    counties: ['GB-SCT'],
    launchYear: null,
    types: ['Public'],
  },
  {
    date: '2023-01-03',
    localName: "New Year's Day",
    name: "New Year's Day",
    countryCode: 'GB',
    fixed: false,
    global: false,
    counties: ['GB-SCT'],
    launchYear: null,
    types: ['Public'],
  },
  {
    date: '2023-03-17',
    localName: "Saint Patrick's Day",
    name: "Saint Patrick's Day",
    countryCode: 'GB',
    fixed: true,
    global: false,
    counties: ['GB-NIR'],
    launchYear: null,
    types: ['Public'],
  },
  {
    date: '2023-04-07',
    localName: 'Good Friday',
    name: 'Good Friday',
    countryCode: 'GB',
    fixed: false,
    global: true,
    counties: null,
    launchYear: null,
    types: ['Public'],
  },
  {
    date: '2023-04-10',
    localName: 'Easter Monday',
    name: 'Easter Monday',
    countryCode: 'GB',
    fixed: false,
    global: false,
    counties: ['GB-ENG', 'GB-WLS', 'GB-NIR'],
    launchYear: null,
    types: ['Public'],
  },
  {
    date: '2023-05-01',
    localName: 'Early May Bank Holiday',
    name: 'Early May Bank Holiday',
    countryCode: 'GB',
    fixed: false,
    global: true,
    counties: null,
    launchYear: 1978,
    types: ['Public'],
  },
  {
    date: '2023-05-08',
    localName: 'Coronation Bank Holiday',
    name: 'Coronation Bank Holiday',
    countryCode: 'GB',
    fixed: true,
    global: true,
    counties: null,
    launchYear: null,
    types: ['Public'],
  },
  {
    date: '2023-05-29',
    localName: 'Spring Bank Holiday',
    name: 'Spring Bank Holiday',
    countryCode: 'GB',
    fixed: false,
    global: true,
    counties: null,
    launchYear: 1971,
    types: ['Public'],
  },
  {
    date: '2023-07-12',
    localName: 'Battle of the Boyne',
    name: 'Battle of the Boyne',
    countryCode: 'GB',
    fixed: true,
    global: false,
    counties: ['GB-NIR'],
    launchYear: null,
    types: ['Public'],
  },
  {
    date: '2023-08-07',
    localName: 'Summer Bank Holiday',
    name: 'Summer Bank Holiday',
    countryCode: 'GB',
    fixed: false,
    global: false,
    counties: ['GB-SCT'],
    launchYear: 1971,
    types: ['Public'],
  },
  {
    date: '2023-08-28',
    localName: 'Summer Bank Holiday',
    name: 'Summer Bank Holiday',
    countryCode: 'GB',
    fixed: false,
    global: false,
    counties: ['GB-ENG', 'GB-WLS', 'GB-NIR'],
    launchYear: 1971,
    types: ['Public'],
  },
  {
    date: '2023-11-30',
    localName: "Saint Andrew's Day",
    name: "Saint Andrew's Day",
    countryCode: 'GB',
    fixed: true,
    global: false,
    counties: ['GB-SCT'],
    launchYear: null,
    types: ['Public'],
  },
  {
    date: '2023-12-25',
    localName: 'Christmas Day',
    name: 'Christmas Day',
    countryCode: 'GB',
    fixed: false,
    global: true,
    counties: null,
    launchYear: null,
    types: ['Public'],
  },
  {
    date: '2023-12-26',
    localName: 'Boxing Day',
    name: "St. Stephen's Day",
    countryCode: 'GB',
    fixed: false,
    global: true,
    counties: null,
    launchYear: null,
    types: ['Public'],
  },
]

export const SHORT_PUBLIC_HOLIDAY_LIST_GB = [
  {
    name: "New Year's Day",
    localName: "New Year's Day",
    date: '2023-01-01',
  },
  {
    name: "New Year's Day",
    localName: "New Year's Day",
    date: '2023-01-02',
  },
  {
    name: "New Year's Day",
    localName: "New Year's Day",
    date: '2023-01-02',
  },
  {
    name: "New Year's Day",
    localName: "New Year's Day",
    date: '2023-01-03',
  },
  {
    name: "Saint Patrick's Day",
    localName: "Saint Patrick's Day",
    date: '2023-03-17',
  },
  { name: 'Good Friday', localName: 'Good Friday', date: '2023-04-07' },
  {
    name: 'Easter Monday',
    localName: 'Easter Monday',
    date: '2023-04-10',
  },
  {
    name: 'Early May Bank Holiday',
    localName: 'Early May Bank Holiday',
    date: '2023-05-01',
  },
  {
    name: 'Coronation Bank Holiday',
    localName: 'Coronation Bank Holiday',
    date: '2023-05-08',
  },
  {
    name: 'Spring Bank Holiday',
    localName: 'Spring Bank Holiday',
    date: '2023-05-29',
  },
  {
    name: 'Battle of the Boyne',
    localName: 'Battle of the Boyne',
    date: '2023-07-12',
  },
  {
    name: 'Summer Bank Holiday',
    localName: 'Summer Bank Holiday',
    date: '2023-08-07',
  },
  {
    name: 'Summer Bank Holiday',
    localName: 'Summer Bank Holiday',
    date: '2023-08-28',
  },
  {
    name: "Saint Andrew's Day",
    localName: "Saint Andrew's Day",
    date: '2023-11-30',
  },
  {
    name: 'Christmas Day',
    localName: 'Christmas Day',
    date: '2023-12-25',
  },
  {
    name: "St. Stephen's Day",
    localName: 'Boxing Day',
    date: '2023-12-26',
  },
]
